# NUMPY
### Numpy-numerical python
#### A package for scientific computing with python and designed for fast numerical computing

In [5]:
import numpy as np
import time

#Why np arrays is preferred over py list : Execution time comparison
size=100_000_00 #1 million

python_list = list(range(size))
start=time.time()
squared_list=[x**2 for x in python_list]
end = time.time()
print("Python list time: ", end - start,"seconds")

np_array= np.array(python_list)
start=time.time()
squared_np_array=np_array**2 #vectorised operation
end=time.time()
print("Np array time: ", end - start,"seconds")


Python list time:  2.7063868045806885 seconds
Np array time:  0.06755304336547852 seconds


In [8]:
import sys #Size comparison
print("Python list size:", sys.getsizeof(python_list) * len(python_list))
print("NumPy array size:", np_array.nbytes)

Python list size: 800000560000000
NumPy array size: 80000000


## Numpy Arrays

In [11]:
#creating np arrays from list
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

arr_2 =np.array([6,7,8,9,10])
print(arr_2,type(arr_2))

#2d array matrix
arr_3 =np.array([[1,2,3,4,5] ,[6,7,8,9,10]])
print(arr_3,arr_3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
[ 6  7  8  9 10] <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [16]:
#creating np array from scratch
arr_1=np.zeros((3,4)) #filled with 0
print(arr_1,arr_1.shape)

arr_2=np.ones((3,4)) #filled with 1
print(arr_2,arr_2.shape)

arr_3=np.full((2,3),5) #filled with that particular number
print(arr_3,arr_3.shape)

arr_4=np.eye(3) #identity matrix: diagonal values are 1 and others are 0
print(arr_4,arr_4.shape)

arr_5=np.arange(1,11,2) #elements in range
print(arr_5,arr_5.shape)

arr_6=np.linspace(1,100,5) #evenly spaced array
print(arr_6,arr_6.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.    25.75  50.5   75.25 100.  ] (5,)


In [19]:
#Array properties
arr = np.array([[1,2,3] ,[4,5,6],[7,8,9],[10,11,12]])

print(arr.shape) #print dimensions
print(arr.size) #total elements
print(arr.dtype) #data type objects
print(arr.ndim) #total number of dimensions

str_array = np.array([1,2,3,4] ,dtype="U") #u means unicode string: converts everything to string
print(str_array , str_array.dtype)

float_array = np.array([1,2,3,4],dtype="float64") #converts into float
print(float_array, float_array.dtype)

int_array = float_array.astype(np.int64) #converts type from float to int
print(int_array, int_array.dtype)

(4, 3)
12
int64
2
['1' '2' '3' '4'] <U1
[1. 2. 3. 4.] float64
[1 2 3 4] int64


### Operations in Array

In [22]:
#Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

reshaped= arr.reshape((2,3)) #changes dimensions of array
print(reshaped,reshaped.shape)

flattened= reshaped.flatten() #converts from 2d to 1d
print(flattened,flattened.shape)

(6,)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [25]:
#indexing
arr=np.array([1,2,3,4,5,6]) #1d array
print(arr[3])

arr_2=np.array([[1,2,3],[4,5,6]]) #2d array
print(arr_2[0][1])

#fancy indexing: prints value of said index
arr_3=np.array([1,3,4,2,5,7])
idx=[0,3,5]
print(arr[idx])

#boolean indexing: prints asked conditions
print(arr_3[arr_3>2])
print(arr[arr%2])

4
2
[1 4 6]
[3 4 5 7]
[2 1 2 1 2 1]


In [26]:
#slicing
arr=np.array([1,2,3,4,5,6])

print(arr[2:6]) #[3, 4, 5, 6
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6]
[1 3 5]


In [28]:
#copy vs view by slicing
py_list=[1,2,3,4]
copy_list=py_list[1:3]
copy_list[1]=7

print(copy_list)
print(py_list)

np_array=np.array([5,6,7,8]) #np arrays uses view and doesn't create copies it edits the original array which 
view_array=np_array[1:4]
view_array[1]=3

print(view_array)
print(np_array)

#creating a copy of np arrays
copy_array=np_array[1:4].copy()
copy_array[2]=89
print(copy_array)
print(np_array)

[2, 7]
[1, 2, 3, 4]
[6 3 8]
[5 6 3 8]
[ 6  3 89]
[5 6 3 8]
