# NUMPY
### Numpy-numerical python
#### A package for scientific computing with python and designed for fast numerical computing

In [7]:
import numpy as np
import time

#Why np arrays is preferred over py list : Execution time comparison
size=100_000_00 #1 million

python_list = list(range(size))
start=time.time()
squared_list=[x**2 for x in python_list]
end = time.time()
print("Python list time: ", end - start,"seconds")

np_array= np.array(python_list)
start=time.time()
squared_np_array=np_array**2 #vectorised operation
end=time.time()
print("Np array time: ", end - start,"seconds")


Python list time:  2.3665030002593994 seconds
Np array time:  0.08163309097290039 seconds


In [8]:
import sys #Size comparison
print("Python list size:", sys.getsizeof(python_list) * len(python_list))
print("NumPy array size:", np_array.nbytes)

Python list size: 800000560000000
NumPy array size: 80000000


## Numpy Arrays

In [11]:
#creating np arrays from list
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

arr_2 =np.array([6,7,8,9,10])
print(arr_2,type(arr_2))

#2d array matrix
arr_3 =np.array([[1,2,3,4,5] ,[6,7,8,9,10]])
print(arr_3,arr_3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
[ 6  7  8  9 10] <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [16]:
#creating np array from scratch
arr_1=np.zeros((3,4)) #filled with 0
print(arr_1,arr_1.shape)

arr_2=np.ones((3,4)) #filled with 1
print(arr_2,arr_2.shape)

arr_3=np.full((2,3),5) #filled with that particular number
print(arr_3,arr_3.shape)

arr_4=np.eye(3) #identity matrix: diagonal values are 1 and others are 0
print(arr_4,arr_4.shape)

arr_5=np.arange(1,11,2) #elements in range
print(arr_5,arr_5.shape)

arr_6=np.linspace(1,100,5) #evenly spaced array
print(arr_6,arr_6.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.    25.75  50.5   75.25 100.  ] (5,)


In [19]:
#Array properties
arr = np.array([[1,2,3] ,[4,5,6],[7,8,9],[10,11,12]])

print(arr.shape) #print dimensions
print(arr.size) #total elements
print(arr.dtype) #data type objects
print(arr.ndim) #total number of dimensions

str_array = np.array([1,2,3,4] ,dtype="U") #u means unicode string: converts everything to string
print(str_array , str_array.dtype)

float_array = np.array([1,2,3,4],dtype="float64") #converts into float
print(float_array, float_array.dtype)

int_array = float_array.astype(np.int64) #converts type from float to int
print(int_array, int_array.dtype)

(4, 3)
12
int64
2
['1' '2' '3' '4'] <U1
[1. 2. 3. 4.] float64
[1 2 3 4] int64


### Operations in Array

In [22]:
#Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

reshaped= arr.reshape((2,3)) #changes dimensions of array
print(reshaped,reshaped.shape)

flattened= reshaped.flatten() #converts from 2d to 1d
print(flattened,flattened.shape)

(6,)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [25]:
#indexing
arr=np.array([1,2,3,4,5,6]) #1d array
print(arr[3])

arr_2=np.array([[1,2,3],[4,5,6]]) #2d array
print(arr_2[0][1])

#fancy indexing: prints value of said index
arr_3=np.array([1,3,4,2,5,7])
idx=[0,3,5]
print(arr[idx])

#boolean indexing: prints asked conditions
print(arr_3[arr_3>2])
print(arr[arr%2])

4
2
[1 4 6]
[3 4 5 7]
[2 1 2 1 2 1]


In [26]:
#slicing
arr=np.array([1,2,3,4,5,6])

print(arr[2:6]) #[3, 4, 5, 6
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6]
[1 3 5]


In [29]:
#copy vs view by slicing
py_list=[1,2,3,4]
copy_list=py_list[1:3]
copy_list[1]=7

print(copy_list)
print(py_list)

np_array=np.array([5,6,7,8]) #np arrays uses view and doesn't create copies it edits the original array which results in less space and fast execution
view_array=np_array[1:4]
view_array[1]=3

print(view_array)
print(np_array)

#creating a copy of np arrays
copy_array=np_array[1:4].copy()
copy_array[2]=89
print(copy_array)
print(np_array)

[2, 7]
[1, 2, 3, 4]
[6 3 8]
[5 6 3 8]
[ 6  3 89]
[5 6 3 8]


***
## Axes in Multi-dimensional arrays
- 1D array has 1 axis (axis0).
- 2D array has 2 axes (axis0 = rows, axis1 = columns)
- 3D array has 3 axes (axis0 = depth/layer, axis1 = rows in each layer, axis2 = columns in each layer)

In [8]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D)
print(np.sum(arr2D)) #sum of entire array

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

# Slicing
print(arr2D[0:3, 1:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [9]:
#3d array
arr3d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d)
print(arr3d.shape)

#Indexing
print(arr3d[0][1][1])
print(arr3d[1][2][1])

print(arr3d[:, :, 0])        #first col from both layers
print(arr3d[:, 0, :])        #first row from both layers

#manipulating data
arr3d[:,0,:]=99
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


***
### Common Data Types in Numpy
- Integers: int32, int64
- Floating point nums: float32, float64
- Boolean: bool
- Complex nums: complex64, complex128
- String: S (byte-str) & U (unicode-str)
- Object: generic python objects - object

In [10]:
#common data types
arr=np.array([1,2,3,4,5,6])
arr1=np.array([1.0,2.0,3.0])
arr2=np.array(["hello","my","name","is","Mahak"])

print(arr.dtype)
print(arr1.dtype)
print(arr2.dtype)

print(arr.nbytes)  # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)

#complex numbers
arr1=np.array([2+3j])
arr2=np.array([3+4j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

#objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

int64
float64
<U5
48
[1. 2. 3. 4. 5. 6.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[5.+7.j]
[1.+1.j]
['hello' {1, 2, 3} 3.14] object


***

### Vectorization & Broadcasting

<b>1. Vectorization</b>: It is the process of applying operations to entire arrays or sequences of data at once, rather than iterating through individual elements using explicit loops. 

<b>2. Broadcasting</b>: It is a mechanism that allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them (creating copies of the smaller array to match the larger array's shape). 

<b> Broadcasting Condition <b>

For broadcasting to happen the dimensions should be compatible. Numpy compares shape element-wise. It starts dimension comparison with the trailing (i.e. rightmost) dimension and works its way left. 
Two dimensions are compatible when <ol> <li>they are equal, or</li> <li>one of them is 1. </li>

In [12]:
#Vectorization
arr=np.array([1,2,3,4,5])
sq_arr=arr**2
print(arr,sq_arr)

arr1=np.array([2,4,6,8,10])
print(arr+arr1)

#broadcasting
arr_mul_10= arr*10
print(arr_mul_10)

arr1d=np.array([1,2,3,4,5])
arr2d=np.array([[6,7,8,9,10],[11,12,13,14,15]])
print(arr1d+arr2d)

[1 2 3 4 5] [ 1  4  9 16 25]
[ 3  6  9 12 15]
[10 20 30 40 50]
[[ 7  9 11 13 15]
 [12 14 16 18 20]]


In [13]:
#vector normalisation
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

print((arr - mean) / std_dev)

#column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


***

### Mathematical Functions in NumPy
There are lots of important & commonly used mathematical functions in NumPy.
1. Aggregation functions
   - sum()
   - prod()
   - min() & argmin() - min val & idx of min val
   - max() & argmax() - max val & idx of max val
   - mean()
   - median()
   - std() - standard deviation
   - var() - variance

In [14]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5,6])

print(np.sum(arr))     
print(np.prod(arr))    
print(np.min(arr))     
print(np.argmin(arr))  
print(np.max(arr))     
print(np.argmax(arr))  
print(np.mean(arr))    
print(np.median(arr))  
print(np.std(arr))     
print(np.var(arr))     

21
720
1
0
6
5
3.5
3.5
1.707825127659933
2.9166666666666665


2. Power functions
   - square()
   - sqrt() - square root
   - pow(a, b) - a^b

In [15]:
print(np.square(arr))    
print(np.sqrt(arr))      
print(np.pow(arr, 3))

[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  1   8  27  64 125 216]


3. Log & Exponential functions
   - log() - natual log
   - log10() - log base 10
   - log2() - log base 2
   - exp() - exponentional i.e. e^x

In [16]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


4. Rounding functions
   - round() - rounds to nearest value
   - floor() - rounds down
   - ceil() - rounds up
   - trunc() - truncates decimal part

In [17]:
print(np.round(2.678))    
print(np.floor(2.678))    
print(np.ceil(2.678))     
print(np.trunc(2.678))  

3.0
2.0
3.0
2.0


5. Additional functions
   - abs() - absolute value
   - sort()
   - unique() - returns unique values

In [18]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     
print(np.sort(arr))    
print(np.unique(arr))

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
